//
//  GooglePlacesTypes.h
//  JMMLocationEngine
//
//  Created by M. Arsalan Anwar on 07/12/2013.
//  Copyright (c) 2013 O16 Labs. All rights reserved.
//

#ifndef JMMLocationEngine_GooglePlacesTypes_h
#define JMMLocationEngine_GooglePlacesTypes_h

#define kGooglePlacesTypeAccounting     @"accounting"
#define kGooglePlacesTypeAirport        @"airport"
#define kGooglePlacesTypeAmusementPark  @"amusement_park"
#define kGooglePlacesTypeAquarium       @"aquarium"
#define kGooglePlacesTypeArtGallery 	@"art_gallery"
#define kGooglePlacesTypeAtm			@"atm"
#define kGooglePlacesTypeBakery 		@"bakery"
#define kGooglePlacesTypeBank 			@"bank"
#define kGooglePlacesTypeBar            @"bar"
#define kGooglePlacesTypeBeautySalon    @"beauty_salon"
#define kGooglePlacesTypeBicycleStore   @"bicycle_store"
#define kGooglePlacesTypeBookStore      @"book_store"
#define kGooglePlacesTypeBowlingAlley   @"bowling_alley"
#define kGooglePlacesTypeBowlingAlley   @"bowling_alley"
#define kGooglePlacesTypeCafe           @"cafe"
#define kGooglePlacesTypeCampground     @"campground"
#define kGooglePlacesTypeCarDealer      @"car_dealer"
#define kGooglePlacesTypeCarRental      @"car_rental"
#define kGooglePlacesTypeCarRepair      @"car_repair"
#define kGooglePlacesTypeCarWash        @"car_wash"
#define kGooglePlacesTypeCasino         @"casino"
#define kGooglePlacesTypeCemetery       @"cemetery"
#define kGooglePlacesTypeChurch         @"church"
#define kGooglePlacesTypeCityHall       @"city_hall"
#define kGooglePlacesTypeClothingStore  @"clothing_store"
#define kGooglePlacesTypeConvenienceStore @"convenience_store"
#define kGooglePlacesTypeCourthouse     @"courthouse"
#define kGooglePlacesTypeDentist        @"dentist"
#define kGooglePlacesTypeDepartmentStore @"department_store"
#define kGooglePlacesTypeDoctor         @"doctor"
#define kGooglePlacesTypeElectrician    @"electrician"
#define kGooglePlacesTypeElectronicsStore @"electronics_store"
#define kGooglePlacesTypeEmbassy        @"embassy"
#define kGooglePlacesTypeEstablishment  @"establishment"
#define kGooglePlacesTypeFinance        @"finance"
#define kGooglePlacesTypeFireStation    @"fire_station"
#define kGooglePlacesTypeFlorist        @"florist"
#define kGooglePlacesTypeFood           @"food"
#define kGooglePlacesTypeFuneralHome    @"funeral_home"
#define kGooglePlacesTypeFurnitureStore @"furniture_store"
#define kGooglePlacesTypeGasStation     @"gas_station"
#define kGooglePlacesTypeGeneralContractor @"general_contractor"
#define kGooglePlacesTypeGroceryORSupermarket @"grocery_or_supermarket"
#define kGooglePlacesTypeGym            @"gym"
#define kGooglePlacesTypeHairCare       @"hair_care"
#define kGooglePlacesTypeHardwareStore  @"hardware_store"
#define kGooglePlacesTypeHealth         @"health"
#define kGooglePlacesTypeHinduTemple    @"hindu_temple"
#define kGooglePlacesTypeHomeGoodsStore @"home_goods_store"
#define kGooglePlacesTypeHospital       @"hospital"
#define kGooglePlacesTypeInsuranceAgency @"insurance_agency"
#define kGooglePlacesTypeJewelryStore   @"jewelry_store"
#define kGooglePlacesTypeLaundry        @"laundry"
#define kGooglePlacesTypeLawyer         @"lawyer"
#define kGooglePlacesTypeLibrary        @"library"
#define kGooglePlacesTypeLiquorStore    @"liquor_store"
#define kGooglePlacesTypeLocalGovernmentOffice @"local_government_office"
#define kGooglePlacesTypeLocksmith      @"locksmith"
#define kGooglePlacesTypeLodging        @"lodging"
#define kGooglePlacesTypeMealDelivery   @"meal_delivery"
#define kGooglePlacesTypeMealTakeaway   @"meal_takeaway"
#define kGooglePlacesTypeMosque         @"mosque"
#define kGooglePlacesTypeMovieRental    @"movie_rental"
#define kGooglePlacesTypeMovieTheater   @"movie_theater"
#define kGooglePlacesTypeMovingCompany  @"moving_company"
#define kGooglePlacesTypeMuseum         @"museum"
#define kGooglePlacesTypeNightClub      @"night_club"
#define kGooglePlacesTypePainter        @"painter"
#define kGooglePlacesTypePark           @"park"
#define kGooglePlacesTypeParking        @"parking"
#define kGooglePlacesTypePetStore       @"pet_store"
#define kGooglePlacesTypePharmacy       @"pharmacy"
#define kGooglePlacesTypePhysiotherapist @"physiotherapist"
#define kGooglePlacesTypePlaceOfWorship  @"place_of_worship"
#define kGooglePlacesTypePlumber        @"plumber"
#define kGooglePlacesTypePolice         @"police"
#define kGooglePlacesTypePostOffice     @"post_office"
#define kGooglePlacesTypeRealEstateAgency @"real_estate_agency"
#define kGooglePlacesTypeRestaurant     @"restaurant"
#define kGooglePlacesTypeRoofingContractor @"roofing_contractor"
#define kGooglePlacesTypeRvPark         @"rv_park"
#define kGooglePlacesTypeSchool         @"school"
#define kGooglePlacesTypeShoeStore      @"shoe_store"
#define kGooglePlacesTypeShoppingMall   @"shopping_mall"
#define kGooglePlacesTypeSpa            @"spa"
#define kGooglePlacesTypeStadium        @"stadium"
#define kGooglePlacesTypeStorage        @"storage"
#define kGooglePlacesTypeStore          @"store"
#define kGooglePlacesTypeSubwayStation  @"subway_station"
#define kGooglePlacesTypeSynagogue      @"synagogue"
#define kGooglePlacesTypeTaxiStand      @"taxi_stand"
#define kGooglePlacesTypeTrainStation   @"train_station"
#define kGooglePlacesTypeTravelAgency   @"travel_agency"
#define kGooglePlacesTypeUniversity     @"university"
#define kGooglePlacesTypeVeterinaryCare @"veterinary_care"
#define kGooglePlacesTypeZoo            @"zoo"


#endif
